#!/usr/bin/env bash
# Purpose: clean boltorezka server logs older than retention window (default: 1 day).
set -euo pipefail

BASE_DIR="${BOLTOREZKA_BASE_DIR:-$HOME/srv/boltorezka}"
EDGE_DIR="${EDGE_BASE_DIR:-$HOME/srv/edge}"
RETENTION_DAYS="${LOG_RETENTION_DAYS:-1}"

if [[ ! "$RETENTION_DAYS" =~ ^[0-9]+$ ]]; then
  echo "[log-cleanup] LOG_RETENTION_DAYS must be a non-negative integer" >&2
  exit 1
fi

cleanup_dir() {
  local dir="$1"
  local pattern="$2"
  if [[ -d "$dir" ]]; then
    find "$dir" -type f -name "$pattern" -mtime "+$RETENTION_DAYS" -print -delete || true
  fi
}

# Deploy/smoke logs in boltorezka repo.
cleanup_dir "$BASE_DIR/.deploy" "*.log"
cleanup_dir "$BASE_DIR/.deploy" "*.tsv"
cleanup_dir "$BASE_DIR/.deploy" "*.out"
cleanup_dir "$BASE_DIR/.deploy" "*.err"

# launchd and maintenance logs from edge contour.
cleanup_dir "$EDGE_DIR/logs" "*.log"
cleanup_dir "$EDGE_DIR/logs" "*.out"
cleanup_dir "$EDGE_DIR/logs" "*.err"

# Temporary smoke/deploy logs generated by ad-hoc runs.
find /tmp -maxdepth 1 -type f \( -name 'livekit-media-smoke*.log' -o -name 'deploy-livekit*.log' -o -name 'boltorezka-smoke*.log' \) -mtime "+$RETENTION_DAYS" -print -delete || true

echo "[log-cleanup] done (retention_days=$RETENTION_DAYS)"
