import { useRef } from "react";
import {
  RealtimeClient
} from "./services";
import {
  AppShellLayout
} from "./components";
import {
  DEFAULT_CHAT_IMAGE_DATA_URL_LENGTH,
  DEFAULT_CHAT_IMAGE_MAX_SIDE,
  DEFAULT_CHAT_IMAGE_QUALITY,
  MAX_CHAT_RETRIES,
  MESSAGE_EDIT_DELETE_WINDOW_MS,
  PENDING_ACCESS_AUTO_REFRESH_SEC,
  VERSION_UPDATE_PENDING_KEY
} from "./constants/appConfig";
import {
  useAppCoreState,
  useAppUiState,
  useAppAuthWorkspaceRuntime,
  useAppEntryGatesState,
  useAppRealtimeTransportRuntime,
  useAppVoiceMediaRuntime,
  useAppPermissionsIdentityRuntime,
  useAppRefsAndAdaptersRuntime,
  useAppRoomsRuntime,
  useAppShellRuntime,
  useAppShellRuntimeInput,
  useAppWorkspaceActionsRuntime,
  useAppWorkspaceActionsRuntimeInput,
  useAppUserDockSharedProps,
  useAppUserMediaState,
  useAppWorkspacePanelsRuntime,
  useAppWorkspacePanelsRuntimeInput,
  useAppWorkspaceLifecycleGuardsRuntime,
  useAppControllersRuntime,
  useAppInviteServerSyncRuntime,
  useAppShellRoomRuntimeEffects,
  useAppEventLogs,
  useBuildVersionSync,
  useOnboardingOverlayActions,
  useAppWorkspaceSupportRuntime,
  useCollapsedCategories,
  useRoomEditorState,
  useServerSounds,
  useToastQueue
} from "./hooks";
import { formatBuildDateLabel } from "./utils/appShell";

const CLIENT_BUILD_VERSION = String(import.meta.env.VITE_APP_VERSION || "").trim();
const CLIENT_BUILD_SHA = String(import.meta.env.VITE_APP_BUILD_SHA || CLIENT_BUILD_VERSION || "").trim();
const CLIENT_BUILD_DATE = String(import.meta.env.VITE_APP_BUILD_DATE || "").trim();
const CLIENT_BUILD_DATE_LABEL = formatBuildDateLabel(CLIENT_BUILD_VERSION, CLIENT_BUILD_DATE);
const CHAT_TYPING_TTL_MS = 4500;
const CHAT_TYPING_PING_INTERVAL_MS = 1800;
const COOKIE_CONSENT_KEY = "boltorezka_cookie_consent_v1";
const CURRENT_SERVER_ID_STORAGE_KEY = "boltorezka_current_server_id";
const ROOM_SLUG_STORAGE_KEY = "boltorezka_room_slug";

// IMPORTANT: `App` is an orchestration boundary only.
// Do not add new business logic, parsing, transport rules, or large feature workflows here.
// Put feature logic into dedicated hooks/services/components and keep this file as glue code.
export function App() {
  const {
    token, setToken,
    user, setUser,
    authMode, setAuthMode,
    rooms, setRooms,
    roomsTree, setRoomsTree,
    archivedRooms, setArchivedRooms,
    roomSlug, setRoomSlug,
    chatRoomSlug, setChatRoomSlug,
    showAppUpdatedOverlay, setShowAppUpdatedOverlay,
    cookieConsentAccepted, setCookieConsentAccepted,
    pendingAccessRefreshInSec, setPendingAccessRefreshInSec,
    showFirstRunIntro, setShowFirstRunIntro,
    sessionMovedOverlayMessage, setSessionMovedOverlayMessage,
    messages, setMessages,
    messagesHasMore, setMessagesHasMore,
    messagesNextCursor, setMessagesNextCursor,
    loadingOlderMessages, setLoadingOlderMessages,
    chatText, setChatText,
    pendingChatImageDataUrl, setPendingChatImageDataUrl,
    editingMessageId, setEditingMessageId,
    callStatus, setCallStatus,
    lastCallPeer, setLastCallPeer,
    roomsPresenceBySlug, setRoomsPresenceBySlug,
    roomsPresenceDetailsBySlug, setRoomsPresenceDetailsBySlug,
    memberPreferencesByUserId, setMemberPreferencesByUserId,
    roomMediaTopologyBySlug, setRoomMediaTopologyBySlug,
    servers, setServers,
    serversLoading, setServersLoading,
    currentServerId, setCurrentServerId,
    creatingServer, setCreatingServer,
    serverMembers, setServerMembers,
    serverMembersLoading, setServerMembersLoading,
    lastInviteUrl, setLastInviteUrl,
    creatingInvite, setCreatingInvite,
    serverAgeLoading, setServerAgeLoading,
    serverAgeConfirmedAt, setServerAgeConfirmedAt,
    serverAgeConfirming, setServerAgeConfirming,
    ageGateBlockedRoomSlug, setAgeGateBlockedRoomSlug,
    pendingInviteToken, setPendingInviteToken,
    inviteAccepting, setInviteAccepting,
    telemetrySummary, setTelemetrySummary,
    wsState, setWsState,
    adminUsers, setAdminUsers,
    adminServers, setAdminServers,
    adminServersLoading, setAdminServersLoading,
    selectedAdminServerId, setSelectedAdminServerId,
    adminServerOverview, setAdminServerOverview,
    adminServerOverviewLoading, setAdminServerOverviewLoading
  } = useAppCoreState({
    versionUpdatePendingKey: VERSION_UPDATE_PENDING_KEY,
    cookieConsentKey: COOKIE_CONSENT_KEY,
    currentServerIdStorageKey: CURRENT_SERVER_ID_STORAGE_KEY,
    pendingAccessAutoRefreshSec: PENDING_ACCESS_AUTO_REFRESH_SEC
  });
  const {
    newRoomSlug, setNewRoomSlug,
    newRoomTitle, setNewRoomTitle,
    newRoomKind, setNewRoomKind,
    newRoomCategoryId, setNewRoomCategoryId,
    newCategorySlug, setNewCategorySlug,
    newCategoryTitle, setNewCategoryTitle,
    categoryPopupOpen, setCategoryPopupOpen,
    channelPopupOpen, setChannelPopupOpen,
    categorySettingsPopupOpenId, setCategorySettingsPopupOpenId,
    editingCategoryTitle, setEditingCategoryTitle,
    channelSettingsPopupOpenId, setChannelSettingsPopupOpenId,
    editingRoomTitle, setEditingRoomTitle,
    editingRoomKind, setEditingRoomKind,
    editingRoomCategoryId, setEditingRoomCategoryId,
    editingRoomNsfw, setEditingRoomNsfw,
    editingRoomAudioQualitySetting,
    setEditingRoomAudioQualitySetting
  } = useRoomEditorState();
  const {
    micMuted, setMicMuted,
    audioMuted, setAudioMuted,
    lang, setLang,
    selectedUiTheme, setSelectedUiTheme,
    profileNameDraft, setProfileNameDraft,
    profileStatusText, setProfileStatusText,
    deleteAccountPending, setDeleteAccountPending,
    deleteAccountStatusText, setDeleteAccountStatusText,
    deletedAccountInfo, setDeletedAccountInfo,
    restoreDeletedAccountPending, setRestoreDeletedAccountPending,
    rnnoiseRuntimeStatus, setRnnoiseRuntimeStatus,
    profileSaving, setProfileSaving,
    inputDevices, setInputDevices,
    outputDevices, setOutputDevices,
    videoInputDevices, setVideoInputDevices,
    selectedInputId, setSelectedInputId,
    selectedOutputId, setSelectedOutputId,
    selectedVideoInputId, setSelectedVideoInputId,
    cameraEnabled, setCameraEnabled,
    screenShareOwnerByRoomSlug, setScreenShareOwnerByRoomSlug,
    voiceCameraEnabledByUserIdInCurrentRoom, setVoiceCameraEnabledByUserIdInCurrentRoom,
    voiceInitialMicStateByUserIdInCurrentRoom, setVoiceInitialMicStateByUserIdInCurrentRoom,
    voiceInitialAudioOutputMutedByUserIdInCurrentRoom, setVoiceInitialAudioOutputMutedByUserIdInCurrentRoom,
    selectedInputProfile, setSelectedInputProfile,
    rnnoiseSuppressionLevel, setRnnoiseSuppressionLevel,
    preRnnEchoCancellationEnabled, setPreRnnEchoCancellationEnabled,
    preRnnAutoGainControlEnabled, setPreRnnAutoGainControlEnabled,
    selfMonitorEnabled, setSelfMonitorEnabled,
    mediaDevicesState, setMediaDevicesState,
    mediaDevicesHint, setMediaDevicesHint,
    micVolume, setMicVolume,
    outputVolume, setOutputVolume,
    micTestLevel, setMicTestLevel,
    serverAudioQuality, setServerAudioQuality,
    serverAudioQualitySaving, setServerAudioQualitySaving,
    serverChatImagePolicy, setServerChatImagePolicy,
    serverVideoEffectType, setServerVideoEffectType,
    serverVideoResolution, setServerVideoResolution,
    serverVideoFps, setServerVideoFps,
    serverScreenShareResolution, setServerScreenShareResolution,
    serverVideoPixelFxStrength, setServerVideoPixelFxStrength,
    serverVideoPixelFxPixelSize, setServerVideoPixelFxPixelSize,
    serverVideoPixelFxGridThickness, setServerVideoPixelFxGridThickness,
    serverVideoAsciiCellSize, setServerVideoAsciiCellSize,
    serverVideoAsciiContrast, setServerVideoAsciiContrast,
    serverVideoAsciiColor, setServerVideoAsciiColor,
    serverVideoWindowMinWidth, setServerVideoWindowMinWidth,
    serverVideoWindowMaxWidth, setServerVideoWindowMaxWidth
  } = useAppUserMediaState();
  const {
    audioOutputMenuOpen, setAudioOutputMenuOpen,
    voiceSettingsOpen, setVoiceSettingsOpen,
    userSettingsOpen, setUserSettingsOpen,
    userSettingsTab, setUserSettingsTab,
    voiceSettingsPanel, setVoiceSettingsPanel,
    authMenuOpen, setAuthMenuOpen,
    profileMenuOpen, setProfileMenuOpen,
    appMenuOpen, setAppMenuOpen,
    serverMenuTab, setServerMenuTab,
    isMobileViewport, setIsMobileViewport,
    mobileTab, setMobileTab,
    videoWindowsVisible,
    setVideoWindowsVisible
  } = useAppUiState();
  const { toasts, pushToast } = useToastQueue();
  const realtimeClientRef = useRef<RealtimeClient | null>(null);

  const {
    canCreateRooms,
    canManageUsers,
    canPromote,
    canUseService,
    serviceToken,
    canManageAudioQuality,
    canManageServerControlPlane,
    canViewTelemetry,
    pendingJoinRequestsCount,
    locale,
    t,
    currentUserId,
    currentUserIdOrNull,
    currentUserName,
    hasUser,
    hasServiceToken
  } = useAppPermissionsIdentityRuntime({
    token,
    user,
    servers,
    currentServerId,
    adminUsers,
    lang,
    pushToast
  });

  const {
    realtimeReconnectNonce,
    bumpRealtimeReconnectNonce,
    currentServerIdRef,
    roomSlugRef,
    lastRoomSlugForScrollRef,
    lastMessageIdRef,
    chatLogRef,
    autoSsoAttemptedRef,
    authMenuRef,
    profileMenuRef,
    categoryPopupRef,
    channelPopupRef,
    audioOutputAnchorRef,
    voiceSettingsAnchorRef,
    userSettingsRef,
    selectChannelPlaceholderMessage,
    serverErrorMessage,
    chatImageTooLargeMessage,
    markMessageDelivery
  } = useAppRefsAndAdaptersRuntime({
    currentServerId,
    roomSlug,
    chatRoomSlug,
    t,
    chatImagePolicy: serverChatImagePolicy,
    setMessages
  });
  const { eventLog, callEventLog, pushLog, pushCallLog } = useAppEventLogs(locale);

  const { collapsedCategoryIds, toggleCategoryCollapsed } = useCollapsedCategories(roomsTree);
  const {
    settings: serverSoundSettings,
    setMasterVolume: setServerSoundsMasterVolume,
    setEventEnabled: setServerSoundEnabled,
    playServerSound
  } = useServerSounds();

  useBuildVersionSync(CLIENT_BUILD_SHA);

  const {
    sendWsEvent,
    sendWsEventAwaitAck,
    handleWsAck,
    handleWsNack,
    setChatTypingByRoomSlug,
    activeChatTypingUsers,
    handleSetChatText,
    sendChatTypingState,
    applyRemoteTypingPayload
  } = useAppRealtimeTransportRuntime({
    wsAcks: {
      realtimeClientRef
    },
    chatTyping: {
      chatRoomSlug,
      userId: user?.id,
      setChatText,
      typingTtlMs: CHAT_TYPING_TTL_MS,
      typingPingIntervalMs: CHAT_TYPING_PING_INTERVAL_MS
    }
  });

  const {
    currentRoomVoiceTargets,
    remoteVideoLabelsByUserId,
    currentRoomSnapshot,
    topologySupportsRtc,
    currentRoomSupportsRtc,
    currentRoomSupportsVideo,
    allowVideoStreaming,
    roomVoiceConnected,
    remoteAudioAutoplayBlocked,
    localVoiceMediaStatusSummary,
    localVideoStream,
    remoteVideoStreamsByUserId,
    connectRoom,
    disconnectRoom,
    handleIncomingRtcVideoState,
    handleCallNack,
    normalizedServerVideoWindowMinWidth,
    normalizedServerVideoWindowMaxWidth,
    setBoundedServerVideoWindowMinWidth,
    setBoundedServerVideoWindowMaxWidth,
    voiceMicStateByUserIdInCurrentRoom,
    voiceAudioOutputMutedByUserIdInCurrentRoom,
    voiceRtcStateByUserIdInCurrentRoom,
    currentRoomScreenShareOwner,
    isCurrentUserScreenShareOwner,
    canToggleScreenShare,
    activeScreenShare,
    handleIncomingScreenShareState,
    handleToggleScreenShare,
    speakingVideoWindowIds,
    effectiveVoiceCameraEnabledByUserIdInCurrentRoom,
    voiceMediaStatusSummaryByUserIdInCurrentRoom,
    serverVideoPreviewStream
  } = useAppVoiceMediaRuntime({
    voiceParticipants: {
      roomsPresenceDetailsBySlug,
      roomSlug,
      currentUserId,
      memberPreferencesByUserId
    },
    roomSnapshot: {
      rooms,
      roomsTree,
      roomSlug,
      roomMediaTopologyBySlug,
      serverAudioQuality
    },
    rnnoiseRuntime: {
      selectedInputProfile,
      setSelectedInputProfile,
      setRnnoiseRuntimeStatus,
      pushToast,
      t
    },
    livekitRuntime: {
      t,
      token: serviceToken,
      localUserId: currentUserId,
      roomSlug,
      videoStreamingEnabled: cameraEnabled,
      videoResolution: serverVideoResolution,
      videoFps: serverVideoFps,
      screenShareResolution: serverScreenShareResolution,
      selectedInputId,
      selectedInputProfile,
      rnnoiseSuppressionLevel,
      preRnnEchoCancellationEnabled,
      preRnnAutoGainControlEnabled,
      selectedOutputId,
      selectedVideoInputId,
      micVolume,
      micMuted,
      audioMuted,
      outputVolume,
      pushToast,
      pushCallLog,
      setCallStatus,
      setLastCallPeer
    },
    serverVideoWindowBounds: {
      minWidth: serverVideoWindowMinWidth,
      maxWidth: serverVideoWindowMaxWidth,
      setMinWidth: setServerVideoWindowMinWidth,
      setMaxWidth: setServerVideoWindowMaxWidth
    },
    voiceRoomLifecycle: {
      roomSlug,
      setCameraEnabled,
      setVideoWindowsVisible,
      setVoiceCameraEnabledByUserIdInCurrentRoom,
      setVoiceInitialMicStateByUserIdInCurrentRoom,
      setVoiceInitialAudioOutputMutedByUserIdInCurrentRoom
    },
    persistedClientSettings: {
      selectedInputProfile,
      rnnoiseSuppressionLevel,
      preRnnEchoCancellationEnabled,
      preRnnAutoGainControlEnabled,
      selfMonitorEnabled,
      micMuted,
      audioMuted,
      cameraEnabled,
      serverVideoEffectType,
      serverVideoResolution,
      serverVideoFps,
      serverScreenShareResolution,
      serverVideoPixelFxStrength,
      serverVideoPixelFxPixelSize,
      serverVideoPixelFxGridThickness,
      serverVideoAsciiCellSize,
      serverVideoAsciiContrast,
      serverVideoAsciiColor,
      serverVideoWindowMinWidth,
      serverVideoWindowMaxWidth
    },
    voiceSignaling: {
      roomSlug,
      micMuted,
      micTestLevel,
      audioMuted,
      canManageAudioQuality,
      serverVideoEffectType,
      serverVideoResolution,
      serverVideoFps,
      serverScreenShareResolution,
      serverVideoPixelFxStrength,
      serverVideoPixelFxPixelSize,
      serverVideoPixelFxGridThickness,
      serverVideoAsciiCellSize,
      serverVideoAsciiContrast,
      serverVideoAsciiColor,
      serverVideoWindowMinWidth,
      serverVideoWindowMaxWidth,
      sendWsEvent
    },
    serverVideoPreview: {
      appMenuOpen,
      serverMenuTab,
      canManageAudioQuality,
      selectedVideoInputId,
      serverVideoResolution,
      serverVideoFps,
      serverVideoEffectType,
      serverVideoPixelFxStrength,
      serverVideoPixelFxPixelSize,
      serverVideoPixelFxGridThickness,
      serverVideoAsciiCellSize,
      serverVideoAsciiContrast,
      serverVideoAsciiColor
    },
    voiceRoomStateMaps: {
      userId: currentUserId,
      micMuted,
      micTestLevel,
      audioMuted,
      callStatus,
      initialMicStateByUserIdInCurrentRoom: voiceInitialMicStateByUserIdInCurrentRoom,
      initialAudioOutputMutedByUserIdInCurrentRoom: voiceInitialAudioOutputMutedByUserIdInCurrentRoom
    },
    screenShare: {
      hasSessionToken: hasServiceToken,
      userId: currentUserId,
      userName: currentUserName,
      t,
      pushToast,
      screenShareOwnerByRoomSlug,
      setScreenShareOwnerByRoomSlug,
      sendWsEventAwaitAck
    },
    voiceMediaUiMaps: {
      currentUserId,
      cameraEnabled
    }
  });

  const {
    authController,
    chatController,
    roomAdminController,
    loadTelemetrySummary,
    loadOlderMessages,
    handleIncomingVideoState,
    handleIncomingMicState,
    handleIncomingInitialCallState,
    handleAudioQualityUpdated
  } = useAppControllersRuntime({
    controllers: {
      token,
      canViewTelemetry,
      pushLog,
      pushToast,
      sendWsEvent,
      sendRoomJoinEvent: (slug) => sendWsEventAwaitAck("room.join", { roomSlug: slug }, { maxRetries: 1 }),
      currentServerIdRef,
      setToken,
      setUser,
      setDeletedAccountInfo,
      setRoomSlug,
      setMessages,
      setMessagesHasMore,
      setMessagesNextCursor,
      setRooms,
      setRoomsTree,
      setArchivedRooms,
      setAdminUsers,
      setLoadingOlderMessages,
      setTelemetrySummary
    },
    incomingCallState: {
      canManageAudioQuality,
      roomSlugRef,
      serverVideoWindowMinWidth,
      serverVideoWindowMaxWidth,
      handleIncomingRtcVideoState,
      setServerVideoEffectType,
      setServerVideoResolution,
      setServerVideoFps,
      setServerScreenShareResolution,
      setServerVideoPixelFxStrength,
      setServerVideoPixelFxPixelSize,
      setServerVideoPixelFxGridThickness,
      setServerVideoAsciiCellSize,
      setServerVideoAsciiContrast,
      setServerVideoAsciiColor,
      setServerVideoWindowMinWidth,
      setServerVideoWindowMaxWidth,
      setVoiceCameraEnabledByUserIdInCurrentRoom,
      setVoiceInitialMicStateByUserIdInCurrentRoom,
      setVoiceInitialAudioOutputMutedByUserIdInCurrentRoom,
      setServerAudioQuality,
      setRooms,
      setRoomsTree
    },
    sessionStateLifecycle: {
      token, setToken,
      currentServerId,
      pushLog,
      realtimeClientRef,
      defaultChatImageDataUrlLength: DEFAULT_CHAT_IMAGE_DATA_URL_LENGTH,
      defaultChatImageMaxSide: DEFAULT_CHAT_IMAGE_MAX_SIDE,
      defaultChatImageQuality: DEFAULT_CHAT_IMAGE_QUALITY,
      
      setUser,
      setRooms,
      setRoomsTree,
      setArchivedRooms,
      setMessages,
      setChatText,
      setPendingChatImageDataUrl,
      setMessagesHasMore,
      setMessagesNextCursor,
      setLoadingOlderMessages,
      setAdminUsers,
      setRoomsPresenceBySlug,
      setRoomsPresenceDetailsBySlug,
      setRoomMediaTopologyBySlug,
      setVoiceCameraEnabledByUserIdInCurrentRoom,
      setVoiceInitialMicStateByUserIdInCurrentRoom,
      setVoiceInitialAudioOutputMutedByUserIdInCurrentRoom,
      setTelemetrySummary,
      setServerAudioQuality,
      setServerAudioQualitySaving,
      setServerChatImagePolicy,
      setDeletedAccountInfo
    },
    realtimeChatRuntime: {
      lifecycleCallbacks: {
        chatRoomSlug,
        roomSlugRef,
        realtimeClientRef,
        disconnectRoom,
        playServerSound,
        setRoomsPresenceBySlug,
        setRoomsPresenceDetailsBySlug,
        setRoomSlug,
        setChatTypingByRoomSlug,
        setSessionMovedOverlayMessage,
        pushLog,
        setMessages,
        setMessagesHasMore,
        setMessagesNextCursor,
        applyRemoteTypingPayload
      },
      realtimeChatLifecycleProps: {
        serviceToken,
        reconnectNonce: realtimeReconnectNonce,
        roomSlug,
        chatRoomSlug,
        messages,
        messagesNextCursor,
        loadingOlderMessages,
        chatLogRef,
        roomSlugRef,
        realtimeClientRef,
        lastRoomSlugForScrollRef,
        lastMessageIdRef,
        setWsState,
        setMessages,
        setRoomSlug,
        setRoomMediaTopologyBySlug,
        setRoomsPresenceBySlug,
        setRoomsPresenceDetailsBySlug,
        pushLog,
        pushCallLog,
        pushToast,
        markMessageDelivery,
        handleCallNack,
        handleWsAck,
        handleWsNack,
        handleIncomingScreenShareState
      }
    }
  });

  const {
    desktopUpdateReadyVersion,
    desktopUpdateApplying,
    desktopUpdateBannerDismissed,
    dismissDesktopUpdateBanner,
    applyDesktopUpdate,
    showDesktopBrowserCompletion,
    desktopHandoffError,
    beginSso,
    logout,
    openUserSettings,
    saveMyProfile,
    restoreDeletedAccount,
    handleDeleteAccount
  } = useAppAuthWorkspaceRuntime({
    desktopUpdate: {
      t,
      pushToast
    },
    desktopHandoffToken: token,
    authProfile: {
      authController,
      token,
      authMode,
      autoSsoAttemptedRef,
      profileNameDraft,
      selectedUiTheme,
      t,
      setAuthMode,
      setAuthMenuOpen,
      setProfileMenuOpen,
      setAudioOutputMenuOpen,
      setVoiceSettingsOpen,
      setVoiceSettingsPanel,
      setUserSettingsTab,
      setUserSettingsOpen,
      setProfileSaving,
      setProfileStatusText,
      setUser,
      pushToast,
      onProfileSaved: bumpRealtimeReconnectNonce
    },
    deletedAccount: {
      token,
      deleteAccountPending,
      restoreDeletedAccountPending,
      setDeleteAccountPending,
      setRestoreDeletedAccountPending,
      setDeleteAccountStatusText,
      setDeletedAccountInfo,
      setToken,
      setUser,
      pushToast,
      t
    }
  });

  useAppShellRoomRuntimeEffects({
    shellLifecycle: {
      lang,
      selectedUiTheme,
      user,
      chatRoomSlug,
      setIsMobileViewport,
      setProfileNameDraft,
      setSelectedUiTheme,
      setProfileStatusText,
      setShowFirstRunIntro,
      setEditingMessageId,
      setPendingChatImageDataUrl
    },
    roomSlugPersistence: {
      currentServerId,
      roomSlug,
      roomSlugStorageKey: ROOM_SLUG_STORAGE_KEY,
      setRoomSlug,
      setChatRoomSlug
    }
  });

  useAppInviteServerSyncRuntime({
    inviteAcceptance: {
      token,
      hasUser,
      pendingInviteToken,
      setPendingInviteToken,
      setInviteAccepting,
      setServers,
      setCurrentServerId,
      pushToast,
      t
    },
    serverDataSync: {
      token,
      hasUser,
      currentServerId,
      selectedAdminServerId,
      canManageServerControlPlane,
      currentServerIdStorageKey: CURRENT_SERVER_ID_STORAGE_KEY,
      setServerAgeConfirmedAt,
      setServerAgeLoading,
      setServers,
      setServersLoading,
      setCurrentServerId,
      setServerMembers,
      setServerMembersLoading,
      setAdminServers,
      setSelectedAdminServerId,
      setAdminServerOverview,
      setAdminServersLoading,
      setAdminServerOverviewLoading,
      pushLog
    }
  });

  const { refreshDevices, requestMediaAccess, requestVideoAccess } = useAppWorkspaceSupportRuntime({
    adminUsersSync: {
      token,
      canManageUsers,
      pushLog,
      setAdminUsers
    },
    telemetryRefresh: {
      token,
      canViewTelemetry,
      wsState,
      setTelemetrySummary,
      loadTelemetrySummary
    },
    realtimeConnectionReset: {
      wsState,
      setRoomsPresenceBySlug,
      setRoomsPresenceDetailsBySlug,
      setRoomMediaTopologyBySlug,
      setScreenShareOwnerByRoomSlug,
      setVoiceInitialMicStateByUserIdInCurrentRoom,
      setVoiceInitialAudioOutputMutedByUserIdInCurrentRoom
    },
    realtimeSoundEffects: {
      wsState,
      roomsPresenceDetailsBySlug,
      roomSlug,
      userId: user?.id,
      messages,
      playServerSound
    },
    voiceUiLifecycle: {
      userSettingsOpen,
      userSettingsTab,
      setSelfMonitorEnabled,
      roomSlug,
      roomMediaTopologyBySlug,
      pushCallLog
    },
    mediaDeviceRuntime: {
      t,
      selectedInputId,
      selectedOutputId,
      selectedVideoInputId,
      micVolume,
      outputVolume,
      setInputDevices,
      setOutputDevices,
      setVideoInputDevices,
      setMediaDevicesState,
      setMediaDevicesHint,
      setSelectedInputId,
      setSelectedOutputId,
      setSelectedVideoInputId,
      hasUser,
      roomVoiceConnected,
      voiceSettingsOpen,
      voiceSettingsPanel: voiceSettingsPanel || "",
      userSettingsOpen,
      userSettingsTab,
      pushToast,
      setMicTestLevel,
      selfMonitorEnabled,
      selectedInputProfile,
      rnnoiseSuppressionLevel
    },
    popupOutsideClose: {
      profileMenuOpen,
      authMenuOpen,
      categoryPopupOpen,
      channelPopupOpen,
      channelSettingsPopupOpenId,
      categorySettingsPopupOpenId,
      audioOutputMenuOpen,
      voiceSettingsOpen,
      userSettingsOpen,
      setProfileMenuOpen,
      setAuthMenuOpen,
      setCategoryPopupOpen,
      setChannelPopupOpen,
      setChannelSettingsPopupOpenId,
      setCategorySettingsPopupOpenId,
      setAudioOutputMenuOpen,
      setVoiceSettingsOpen,
      setUserSettingsOpen,
      profileMenuRef,
      authMenuRef,
      categoryPopupRef,
      channelPopupRef,
      audioOutputAnchorRef,
      voiceSettingsAnchorRef,
      userSettingsRef
    }
  });

  const {
    uncategorizedRooms,
    allRooms,
    currentRoom,
    currentServer,
    activeChatRoom
  } = useAppRoomsRuntime({
    roomsDerived: {
      roomsTree,
      rooms,
      roomSlug
    },
    roomsAndServerDerived: {
      servers,
      currentServerId,
      chatRoomSlug,
      roomSlug,
      setChatRoomSlug
    },
    roomSelectionGuard: {
      roomSlug, setRoomSlug,
      chatRoomSlug, setChatRoomSlug
    }
  });

  const {
    joinRoom,
    leaveRoom,
    kickRoomMember,
    moveRoomMember,
    sendMessage,
    handleChatPaste,
    handleChatInputKeyDown,
    startEditingMessage,
    deleteOwnMessage,
    openRoomChat,
    saveMemberPreference,
    promote,
    demote,
    setUserBan,
    setUserAccessState,
    deleteUser,
    forceDeleteUserNow,
    setServerAudioQualityValue,
    handleCreateServer,
    handleCreateServerInvite,
    handleRenameCurrentServer,
    handleConfirmServerAge,
    handleCopyInviteUrl,
    handleServerChange,
    handleLeaveCurrentServer,
    handleDeleteCurrentServer,
    handleRemoveServerMember,
    handleBanServerMember,
    handleUnbanServerMember,
    handleTransferServerOwnership,
    handleToggleAdminServerBlocked,
    handleDeleteAdminServer,
    createRoom,
    createCategory,
    openCreateChannelPopup,
    openChannelSettingsPopup,
    openCategorySettingsPopup,
    saveCategorySettings,
    moveCategory,
    deleteCategory,
    saveChannelSettings,
    moveChannel,
    deleteChannel,
    clearChannelMessages,
    restoreChannel,
    deleteChannelPermanent
  } = useAppWorkspaceActionsRuntime(useAppWorkspaceActionsRuntimeInput({
    roomSlug,
    canCreateRooms,
    roomAdminController,
    disconnectRoom,
    sendWsEvent,
    pushToast,
    pushLog,
    t,
    setAgeGateBlockedRoomSlug,
    setRoomSlug,
    setChatRoomSlug,
    chatRoomSlug,
    messages,
    setMessages,
    setMessagesHasMore,
    setMessagesNextCursor,
    user,
    token,
    chatText,
    setChatText,
    editingMessageId,
    setEditingMessageId,
    pendingChatImageDataUrl,
    setPendingChatImageDataUrl,
    chatController,
    sendChatTypingState,
    selectChannelPlaceholderMessage,
    serverErrorMessage,
    maxChatRetries: MAX_CHAT_RETRIES,
    messageEditDeleteWindowMs: MESSAGE_EDIT_DELETE_WINDOW_MS,
    serverChatImagePolicy,
    chatImageTooLargeMessage,
    currentUserId,
    roomsPresenceDetailsBySlug,
    setMemberPreferencesByUserId,
    canManageUsers,
    canPromote,
    canManageAudioQuality,
    setServerAudioQuality,
    setServerAudioQualitySaving,
    currentServerId,
    creatingInvite,
    serverAgeConfirming,
    lastInviteUrl,
    setCreatingServer,
    setServers,
    setCurrentServerId,
    setCreatingInvite,
    setLastInviteUrl,
    setServerAgeConfirmedAt,
    setServerMembers,
    setAdminServers,
    setSelectedAdminServerId,
    allRooms,
    archivedRooms,
    newRoomTitle,
    newRoomKind,
    newRoomCategoryId,
    newCategoryTitle,
    editingCategoryTitle,
    categorySettingsPopupOpenId,
    editingRoomTitle,
    editingRoomKind,
    editingRoomCategoryId,
    editingRoomNsfw,
    editingRoomAudioQualitySetting,
    channelSettingsPopupOpenId,
    setNewRoomTitle,
    setChannelPopupOpen,
    setNewCategoryTitle,
    setCategoryPopupOpen,
    setNewRoomCategoryId,
    setEditingRoomTitle,
    setEditingRoomKind,
    setEditingRoomCategoryId,
    setEditingRoomNsfw,
    setEditingRoomAudioQualitySetting,
    setChannelSettingsPopupOpenId,
    setEditingCategoryTitle,
    setCategorySettingsPopupOpenId
  }));

  useAppWorkspaceLifecycleGuardsRuntime({
    pendingAccessAutoRefresh: {
      user,
      resetValue: PENDING_ACCESS_AUTO_REFRESH_SEC,
      setPendingAccessRefreshInSec
    },
    autoRoomVoiceConnection: {
      roomMediaResolved: Boolean(currentRoomSnapshot) || topologySupportsRtc,
      currentRoomSupportsRtc: currentRoomSupportsRtc && !showAppUpdatedOverlay,
      roomVoiceTargetsCount: currentRoomVoiceTargets.length,
      roomVoiceConnected,
      // Keep RTC transport attached while user stays in a voice-enabled room.
      // This avoids false "no RTC" states during presence churn and multi-client switches.
      keepConnectedWithoutTargets: true,
      connectRoom,
      disconnectRoom
    },
    serverMenuAccessGuard: {
      serverMenuTab,
      canManageUsers,
      canManageServerControlPlane,
      canViewTelemetry,
      canManageAudioQuality,
      canManageChatImages: canPromote,
      hasCurrentServer: Boolean(currentServer?.id),
      setServerMenuTab
    },
    screenWakeLockEnabled: Boolean(user && roomSlug && currentRoomSupportsRtc && roomVoiceConnected)
  });

  const { acknowledgeUpdatedApp, completeFirstRunIntro } = useOnboardingOverlayActions({
    token,
    user,
    profileNameDraft,
    selectedUiTheme,
    versionUpdatePendingKey: VERSION_UPDATE_PENDING_KEY,
    setProfileSaving,
    setProfileStatusText,
    setUser,
    setShowFirstRunIntro,
    setShowAppUpdatedOverlay,
    pushToast,
    t
  });

  const userDockSharedProps = useAppUserDockSharedProps({
    t,
    user,
    inputDevices,
    outputDevices,
    videoInputDevices,
    allowVideoStreaming,
    handleToggleScreenShare,
    setMicMuted,
    setAudioMuted,
    setCameraEnabled,
    setRnnoiseRuntimeStatus,
    currentRoom,
    currentRoomSupportsRtc,
    currentRoomSupportsVideo,
    callStatus,
    localVoiceMediaStatusSummary,
    lastCallPeer,
    roomVoiceConnected,
    remoteAudioAutoplayBlocked,
    currentRoomScreenShareOwner,
    screenShareOwnedByCurrentUser: isCurrentUserScreenShareOwner,
    canStartScreenShare: canToggleScreenShare,
    rnnoiseSuppressionLevel,
    rnnoiseRuntimeStatus,
    preRnnEchoCancellationEnabled,
    preRnnAutoGainControlEnabled,
    cameraEnabled,
    micMuted,
    audioMuted,
    audioOutputMenuOpen,
    voiceSettingsOpen,
    userSettingsOpen,
    userSettingsTab,
    voiceSettingsPanel,
    profileNameDraft,
    profileSaving,
    profileStatusText,
    deleteAccountPending,
    deleteAccountStatusText,
    serverAgeLoading,
    serverAgeConfirmedAt,
    serverAgeConfirming,
    lang,
    selectedUiTheme,
    selectedInputId,
    selectedOutputId,
    selectedVideoInputId,
    selectedInputProfile,
    micVolume,
    outputVolume,
    serverSoundSettings,
    micTestLevel,
    mediaDevicesState,
    mediaDevicesHint,
    audioOutputAnchorRef,
    voiceSettingsAnchorRef,
    userSettingsRef,
    setRnnoiseSuppressionLevel,
    setPreRnnEchoCancellationEnabled,
    setPreRnnAutoGainControlEnabled,
    selfMonitorEnabled,
    setSelfMonitorEnabled,
    requestVideoAccess,
    openUserSettings,
    setVoiceSettingsOpen,
    setAudioOutputMenuOpen,
    setVoiceSettingsPanel,
    setUserSettingsOpen,
    setUserSettingsTab,
    setProfileNameDraft,
    setLang,
    setSelectedUiTheme,
    saveMyProfile,
    handleDeleteAccount,
    handleConfirmServerAge,
    setSelectedInputId,
    setSelectedOutputId,
    setSelectedVideoInputId,
    setSelectedInputProfile,
    refreshDevices,
    requestMediaAccess,
    setMicVolume,
    setOutputVolume,
    setServerSoundsMasterVolume,
    setServerSoundEnabled,
    playServerSound,
    leaveRoom,
    isMobileViewport
  });

  const {
    roomsPanelProps,
    serverProfileModalProps,
    chatPanelProps,
    videoWindowsOverlayProps
  } = useAppWorkspacePanelsRuntime(useAppWorkspacePanelsRuntimeInput({
    t,
    canCreateRooms,
    canManageAudioQuality,
    roomsTree,
    roomSlug,
    chatRoomSlug,
    roomMediaTopologyBySlug,
    currentUserIdOrNull,
    roomsPresenceBySlug,
    roomsPresenceDetailsBySlug,
    memberPreferencesByUserId,
    voiceMicStateByUserIdInCurrentRoom,
    effectiveVoiceCameraEnabledByUserIdInCurrentRoom,
    voiceAudioOutputMutedByUserIdInCurrentRoom,
    voiceRtcStateByUserIdInCurrentRoom,
    voiceMediaStatusSummaryByUserIdInCurrentRoom,
    collapsedCategoryIds,
    uncategorizedRooms,
    archivedRooms,
    newCategorySlug,
    newCategoryTitle,
    categoryPopupOpen,
    newRoomSlug,
    newRoomTitle,
    newRoomKind,
    newRoomCategoryId,
    channelPopupOpen,
    categorySettingsPopupOpenId,
    editingCategoryTitle,
    channelSettingsPopupOpenId,
    editingRoomTitle,
    editingRoomKind,
    editingRoomCategoryId,
    editingRoomNsfw,
    editingRoomAudioQualitySetting,
    categoryPopupRef,
    channelPopupRef,
    setCategoryPopupOpen,
    setChannelPopupOpen,
    setNewCategorySlug,
    setNewCategoryTitle,
    setNewRoomSlug,
    setNewRoomTitle,
    setNewRoomKind,
    setNewRoomCategoryId,
    setEditingCategoryTitle,
    setEditingRoomTitle,
    setEditingRoomKind,
    setEditingRoomCategoryId,
    setEditingRoomNsfw,
    setEditingRoomAudioQualitySetting,
    createCategory,
    createRoom,
    openCreateChannelPopup,
    openCategorySettingsPopup,
    openChannelSettingsPopup,
    saveCategorySettings,
    moveCategory,
    deleteCategory,
    saveChannelSettings,
    moveChannel,
    clearChannelMessages,
    deleteChannel,
    restoreChannel,
    deleteChannelPermanent,
    toggleCategoryCollapsed,
    joinRoom,
    openRoomChat,
    kickRoomMember,
    moveRoomMember,
    saveMemberPreference,
    user,
    currentServer,
    canManageUsers,
    canPromote,
    canManageServerControlPlane,
    canViewTelemetry,
    serverMenuTab,
    serverAudioQuality,
    serverAudioQualitySaving,
    serverChatImagePolicy,
    serverVideoEffectType,
    serverVideoResolution,
    serverVideoFps,
    serverScreenShareResolution,
    serverVideoPixelFxStrength,
    serverVideoPixelFxPixelSize,
    serverVideoPixelFxGridThickness,
    serverVideoAsciiCellSize,
    serverVideoAsciiContrast,
    serverVideoAsciiColor,
    normalizedServerVideoWindowMinWidth,
    normalizedServerVideoWindowMaxWidth,
    adminUsers,
    adminServers,
    adminServersLoading,
    selectedAdminServerId,
    adminServerOverview,
    adminServerOverviewLoading,
    currentServerId,
    servers,
    serverMembers,
    serverMembersLoading,
    lastInviteUrl,
    eventLog,
    telemetrySummary,
    callStatus,
    lastCallPeer,
    roomVoiceConnected,
    callEventLog,
    serverVideoPreviewStream,
    setAppMenuOpen,
    setServerMenuTab,
    promote,
    demote,
    setUserBan,
    setUserAccessState,
    deleteUser,
    forceDeleteUserNow,
    setSelectedAdminServerId,
    handleToggleAdminServerBlocked,
    handleDeleteAdminServer,
    handleCreateServerInvite,
    handleCopyInviteUrl,
    handleServerChange,
    handleRenameCurrentServer,
    handleLeaveCurrentServer,
    handleDeleteCurrentServer,
    handleRemoveServerMember,
    handleBanServerMember,
    handleUnbanServerMember,
    handleTransferServerOwnership,
    loadTelemetrySummary,
    setServerAudioQualityValue,
    setServerVideoEffectType,
    setServerVideoResolution,
    setServerVideoFps,
    setServerScreenShareResolution,
    setServerVideoPixelFxStrength,
    setServerVideoPixelFxPixelSize,
    setServerVideoPixelFxGridThickness,
    setServerVideoAsciiCellSize,
    setServerVideoAsciiContrast,
    setServerVideoAsciiColor,
    setBoundedServerVideoWindowMinWidth,
    setBoundedServerVideoWindowMaxWidth,
    creatingInvite,
    locale,
    serviceToken,
    activeChatRoom,
    messages,
    messagesHasMore,
    loadingOlderMessages,
    chatText,
    pendingChatImageDataUrl,
    activeChatTypingUsers,
    chatLogRef,
    loadOlderMessages,
    handleSetChatText,
    handleChatPaste,
    handleChatInputKeyDown,
    sendMessage,
    editingMessageId,
    currentRoomSupportsRtc,
    videoWindowsVisible,
    setVideoWindowsVisible,
    setEditingMessageId,
    startEditingMessage,
    deleteOwnMessage,
    allowVideoStreaming,
    cameraEnabled,
    localVideoStream,
    remoteVideoStreamsByUserId,
    remoteVideoLabelsByUserId,
    activeScreenShare,
    speakingVideoWindowIds
  }));

  const {
    entryGate,
    showEmptyServerOnboarding
  } = useAppEntryGatesState({
    showDesktopBrowserCompletion,
    desktopHandoffError,
    user,
    deletedAccountInfo,
    restoreDeletedAccountPending,
    restoreDeletedAccount,
    logout,
    t,
    canUseService,
    pendingAccessRefreshInSec,
    serversLoading,
    servers
  });

  if (entryGate) {
    return entryGate;
  }

  const {
    appTopChromeProps,
    appMainSectionProps,
    appShellOverlaysProps
  } = useAppShellRuntime(useAppShellRuntimeInput({
    t,
    user,
    currentServer,
    servers,
    currentServerId,
    creatingServer,
    buildDateLabel: CLIENT_BUILD_DATE_LABEL,
    pendingJoinRequestsCount,
    appMenuOpen,
    authMenuOpen,
    profileMenuOpen,
    authMenuRef,
    profileMenuRef,
    beginSso,
    logout,
    openProfileSettings: () => openUserSettings("profile"),
    setCurrentServerId,
    handleCreateServer,
    mediaDevicesState,
    requestMediaAccess,
    remoteAudioAutoplayBlocked,
    audioMuted,
    desktopUpdateReadyVersion,
    desktopUpdateBannerDismissed,
    desktopUpdateApplying,
    dismissDesktopUpdateBanner,
    applyDesktopUpdate,
    setAppMenuOpen,
    setAuthMenuOpen,
    setProfileMenuOpen,
    authMode,
    showEmptyServerOnboarding,
    isMobileViewport,
    mobileTab,
    setMobileTab,
    userDockSharedProps,
    roomsPanelProps,
    chatPanelProps,
    videoWindowsOverlayProps,
    userSettingsOpen,
    inviteAccepting,
    serverProfileModalProps,
    toasts,
    showAppUpdatedOverlay,
    acknowledgeUpdatedApp,
    showFirstRunIntro,
    profileNameDraft,
    setProfileNameDraft,
    profileSaving,
    completeFirstRunIntro,
    sessionMovedOverlayMessage,
    setSessionMovedOverlayMessage,
    ageGateBlockedRoomSlug,
    serverAgeConfirming,
    openUserSettings,
    handleConfirmServerAge,
    setAgeGateBlockedRoomSlug,
    joinRoom,
    lang,
    cookieConsentAccepted,
    cookieConsentKey: COOKIE_CONSENT_KEY,
    setCookieConsentAccepted
  }));

  return <AppShellLayout topChromeProps={appTopChromeProps} mainSectionProps={appMainSectionProps} shellOverlaysProps={appShellOverlaysProps} />;
}
