import type { FormEvent, RefObject } from "react";
import type { Room, RoomKind, RoomsTreeResponse, User } from "../types";

export type InputProfile = "noise_reduction" | "studio" | "custom";
export type VoiceSettingsPanel = "input_device" | "input_profile" | null;

export type DeviceOption = { id: string; label: string };
export type MediaDevicesState = "ready" | "unsupported" | "denied" | "error";

export type UserDockProps = {
  user: User;
  currentRoomSupportsRtc: boolean;
  currentRoomTitle: string;
  micMuted: boolean;
  audioMuted: boolean;
  audioOutputMenuOpen: boolean;
  voiceSettingsOpen: boolean;
  voicePreferencesOpen: boolean;
  voiceSettingsPanel: VoiceSettingsPanel;
  inputOptions: DeviceOption[];
  outputOptions: DeviceOption[];
  selectedInputId: string;
  selectedOutputId: string;
  selectedInputProfile: InputProfile;
  inputProfileLabel: string;
  currentInputLabel: string;
  micVolume: number;
  outputVolume: number;
  mediaDevicesState: MediaDevicesState;
  mediaDevicesHint: string;
  audioOutputAnchorRef: RefObject<HTMLDivElement>;
  voiceSettingsAnchorRef: RefObject<HTMLDivElement>;
  voicePreferencesRef: RefObject<HTMLDivElement>;
  onToggleMic: () => void;
  onToggleAudio: () => void;
  onToggleVoiceSettings: () => void;
  onToggleAudioOutput: () => void;
  onSetVoiceSettingsOpen: (value: boolean) => void;
  onSetAudioOutputMenuOpen: (value: boolean) => void;
  onSetVoiceSettingsPanel: (panel: VoiceSettingsPanel) => void;
  onSetVoicePreferencesOpen: (value: boolean) => void;
  onSetSelectedInputId: (value: string) => void;
  onSetSelectedOutputId: (value: string) => void;
  onSetSelectedInputProfile: (value: InputProfile) => void;
  onSetMicVolume: (value: number) => void;
  onSetOutputVolume: (value: number) => void;
};

export type RoomsPanelProps = {
  canCreateRooms: boolean;
  roomsTree: RoomsTreeResponse | null;
  roomSlug: string;
  activeRoomMembers: string[];
  uncategorizedRooms: Room[];
  newCategorySlug: string;
  newCategoryTitle: string;
  categoryPopupOpen: boolean;
  newRoomSlug: string;
  newRoomTitle: string;
  newRoomKind: RoomKind;
  newRoomCategoryId: string;
  channelPopupOpen: boolean;
  categorySettingsPopupOpenId: string | null;
  editingCategoryTitle: string;
  channelSettingsPopupOpenId: string | null;
  editingRoomTitle: string;
  editingRoomKind: RoomKind;
  editingRoomCategoryId: string;
  categoryPopupRef: RefObject<HTMLDivElement>;
  channelPopupRef: RefObject<HTMLDivElement>;
  onSetCategoryPopupOpen: (value: boolean) => void;
  onSetChannelPopupOpen: (value: boolean) => void;
  onSetNewCategorySlug: (value: string) => void;
  onSetNewCategoryTitle: (value: string) => void;
  onSetNewRoomSlug: (value: string) => void;
  onSetNewRoomTitle: (value: string) => void;
  onSetNewRoomKind: (value: RoomKind) => void;
  onSetNewRoomCategoryId: (value: string) => void;
  onSetEditingCategoryTitle: (value: string) => void;
  onSetEditingRoomTitle: (value: string) => void;
  onSetEditingRoomKind: (value: RoomKind) => void;
  onSetEditingRoomCategoryId: (value: string) => void;
  onCreateCategory: (event: FormEvent) => void;
  onCreateRoom: (event: FormEvent) => void;
  onOpenCreateChannelPopup: (categoryId?: string | null) => void;
  onOpenCategorySettingsPopup: (categoryId: string, categoryTitle: string) => void;
  onOpenChannelSettingsPopup: (room: Room) => void;
  onSaveCategorySettings: (event: FormEvent) => void;
  onMoveCategory: (direction: "up" | "down") => void;
  onDeleteCategory: () => void;
  onSaveChannelSettings: (event: FormEvent) => void;
  onMoveChannel: (direction: "up" | "down") => void;
  onClearChannelMessages: (room: Room) => void;
  onDeleteChannel: (room: Room) => void;
  onJoinRoom: (slug: string) => void;
};
