import type { FormEvent, RefObject } from "react";
import type { Lang, TranslateFn } from "../i18n";
import type { PresenceMember, Room, RoomKind, RoomsTreeResponse, User } from "../domain";

export type InputProfile = "noise_reduction" | "studio" | "custom";
export type VoiceSettingsPanel = "input_device" | "input_profile" | null;

export type DeviceOption = { id: string; label: string };
export type MediaDevicesState = "ready" | "unsupported" | "denied" | "error";

export type UserDockProps = {
  t: TranslateFn;
  user: User;
  currentRoomSupportsRtc: boolean;
  currentRoomTitle: string;
  callStatus: "idle" | "ringing" | "connecting" | "active";
  lastCallPeer: string;
  roomVoiceConnected: boolean;
  micMuted: boolean;
  audioMuted: boolean;
  audioOutputMenuOpen: boolean;
  voiceSettingsOpen: boolean;
  userSettingsOpen: boolean;
  userSettingsTab: "profile" | "sound";
  voiceSettingsPanel: VoiceSettingsPanel;
  profileNameDraft: string;
  profileEmail: string;
  profileSaving: boolean;
  profileStatusText: string;
  selectedLang: Lang;
  languageOptions: Array<{ value: Lang; label: string }>;
  inputOptions: DeviceOption[];
  outputOptions: DeviceOption[];
  selectedInputId: string;
  selectedOutputId: string;
  selectedInputProfile: InputProfile;
  inputProfileLabel: string;
  currentInputLabel: string;
  micVolume: number;
  outputVolume: number;
  micTestLevel: number;
  mediaDevicesState: MediaDevicesState;
  mediaDevicesHint: string;
  audioOutputAnchorRef: RefObject<HTMLDivElement>;
  voiceSettingsAnchorRef: RefObject<HTMLDivElement>;
  userSettingsRef: RefObject<HTMLDivElement>;
  onToggleMic: () => void;
  onToggleAudio: () => void;
  onToggleVoiceSettings: () => void;
  onToggleAudioOutput: () => void;
  onOpenUserSettings: (tab: "profile" | "sound") => void;
  onSetVoiceSettingsOpen: (value: boolean) => void;
  onSetAudioOutputMenuOpen: (value: boolean) => void;
  onSetVoiceSettingsPanel: (panel: VoiceSettingsPanel) => void;
  onSetUserSettingsOpen: (value: boolean) => void;
  onSetUserSettingsTab: (value: "profile" | "sound") => void;
  onSetProfileNameDraft: (value: string) => void;
  onSetSelectedLang: (value: Lang) => void;
  onSaveProfile: (event: FormEvent) => void;
  onSetSelectedInputId: (value: string) => void;
  onSetSelectedOutputId: (value: string) => void;
  onSetSelectedInputProfile: (value: InputProfile) => void;
  onRefreshDevices: () => void;
  onRequestMediaAccess: () => void;
  onSetMicVolume: (value: number) => void;
  onSetOutputVolume: (value: number) => void;
  onDisconnectCall: () => void;
  inlineSettingsMode?: boolean;
};

export type RoomsPanelProps = {
  t: TranslateFn;
  canCreateRooms: boolean;
  roomsTree: RoomsTreeResponse | null;
  roomSlug: string;
  currentUserId: string;
  currentUserName: string;
  liveRoomMembersBySlug: Record<string, string[]>;
  liveRoomMemberDetailsBySlug: Record<string, PresenceMember[]>;
  voiceMicStateByUserIdInCurrentRoom: Record<string, "muted" | "silent" | "speaking">;
  voiceAudioOutputMutedByUserIdInCurrentRoom: Record<string, boolean>;
  voiceRtcStateByUserIdInCurrentRoom: Record<string, "disconnected" | "connecting" | "connected">;
  collapsedCategoryIds: string[];
  uncategorizedRooms: Room[];
  newCategorySlug: string;
  newCategoryTitle: string;
  categoryPopupOpen: boolean;
  newRoomSlug: string;
  newRoomTitle: string;
  newRoomKind: RoomKind;
  newRoomCategoryId: string;
  channelPopupOpen: boolean;
  categorySettingsPopupOpenId: string | null;
  editingCategoryTitle: string;
  channelSettingsPopupOpenId: string | null;
  editingRoomTitle: string;
  editingRoomKind: RoomKind;
  editingRoomCategoryId: string;
  categoryPopupRef: RefObject<HTMLDivElement>;
  channelPopupRef: RefObject<HTMLDivElement>;
  onSetCategoryPopupOpen: (value: boolean) => void;
  onSetChannelPopupOpen: (value: boolean) => void;
  onSetNewCategorySlug: (value: string) => void;
  onSetNewCategoryTitle: (value: string) => void;
  onSetNewRoomSlug: (value: string) => void;
  onSetNewRoomTitle: (value: string) => void;
  onSetNewRoomKind: (value: RoomKind) => void;
  onSetNewRoomCategoryId: (value: string) => void;
  onSetEditingCategoryTitle: (value: string) => void;
  onSetEditingRoomTitle: (value: string) => void;
  onSetEditingRoomKind: (value: RoomKind) => void;
  onSetEditingRoomCategoryId: (value: string) => void;
  onCreateCategory: (event: FormEvent) => void;
  onCreateRoom: (event: FormEvent) => void;
  onOpenCreateChannelPopup: (categoryId?: string | null) => void;
  onOpenCategorySettingsPopup: (categoryId: string, categoryTitle: string) => void;
  onOpenChannelSettingsPopup: (room: Room) => void;
  onSaveCategorySettings: (event: FormEvent) => void;
  onMoveCategory: (direction: "up" | "down") => void;
  onDeleteCategory: () => void;
  onSaveChannelSettings: (event: FormEvent) => void;
  onMoveChannel: (direction: "up" | "down") => void;
  onClearChannelMessages: (room: Room) => void;
  onDeleteChannel: (room: Room) => void;
  onToggleCategoryCollapsed: (categoryId: string) => void;
  onJoinRoom: (slug: string) => void;
};
