import type { FormEvent, RefObject } from "react";
import type { Lang, TranslateFn } from "../i18n";
import type { ChannelAudioQualitySetting, PresenceMember, Room, RoomKind, RoomMemberPreference, RoomsTreeResponse, UiTheme, User } from "../domain";
import type { VoiceMediaStatusSummary } from "../hooks/rtc/voiceCallTypes";
import type { RnnoiseSuppressionLevel } from "../hooks/rtc/rnnoiseAudioProcessor";

export type InputProfile = "noise_reduction" | "studio" | "custom";
export type VoiceSettingsPanel = "input_device" | "input_profile" | null;

export type DeviceOption = { id: string; label: string };
export type MediaDevicesState = "ready" | "unsupported" | "denied" | "error";
export type ServerSoundEvent =
  | "member_join"
  | "member_leave"
  | "server_disconnected"
  | "chat_message"
  | "self_disconnected"
  | "self_joined_channel";

export type UserDockProps = {
  t: TranslateFn;
  user: User;
  currentRoomSupportsRtc: boolean;
  currentRoomTitle: string;
  callStatus: "idle" | "ringing" | "connecting" | "active";
  localVoiceMediaStatusSummary: VoiceMediaStatusSummary;
  lastCallPeer: string;
  roomVoiceConnected: boolean;
  remoteAudioAutoplayBlocked: boolean;
  screenShareActive: boolean;
  screenShareOwnedByCurrentUser: boolean;
  canStartScreenShare: boolean;
  noiseSuppressionEnabled: boolean;
  rnnoiseSuppressionLevel: RnnoiseSuppressionLevel;
  rnnoiseRuntimeStatus: "inactive" | "active" | "unavailable" | "error";
  preRnnEchoCancellationEnabled: boolean;
  preRnnAutoGainControlEnabled: boolean;
  selfMonitorEnabled: boolean;
  walkieTalkieEnabled: boolean;
  walkieTalkieHotkey: string;
  currentRoomSupportsVideo: boolean;
  cameraEnabled: boolean;
  micMuted: boolean;
  audioMuted: boolean;
  audioOutputMenuOpen: boolean;
  voiceSettingsOpen: boolean;
  userSettingsOpen: boolean;
  userSettingsTab: "profile" | "sound" | "camera" | "server_sounds";
  voiceSettingsPanel: VoiceSettingsPanel;
  profileUsername: string;
  profileNameDraft: string;
  profileEmail: string;
  profileSaving: boolean;
  profileStatusText: string;
  deleteAccountPending: boolean;
  deleteAccountStatusText: string;
  serverAgeLoading: boolean;
  serverAgeConfirmedAt: string | null;
  serverAgeConfirming: boolean;
  selectedLang: Lang;
  selectedUiTheme: UiTheme;
  languageOptions: Array<{ value: Lang; label: string }>;
  inputOptions: DeviceOption[];
  outputOptions: DeviceOption[];
  videoInputOptions: DeviceOption[];
  selectedInputId: string;
  selectedOutputId: string;
  selectedVideoInputId: string;
  selectedInputProfile: InputProfile;
  inputProfileLabel: string;
  currentInputLabel: string;
  micVolume: number;
  outputVolume: number;
  serverSoundsMasterVolume: number;
  serverSoundsEnabled: Record<ServerSoundEvent, boolean>;
  micTestLevel: number;
  mediaDevicesState: MediaDevicesState;
  mediaDevicesHint: string;
  audioOutputAnchorRef: RefObject<HTMLDivElement>;
  voiceSettingsAnchorRef: RefObject<HTMLDivElement>;
  userSettingsRef: RefObject<HTMLDivElement>;
  onToggleMic: () => void;
  onToggleAudio: () => void;
  onToggleCamera: () => void;
  onToggleScreenShare: () => void;
  onToggleNoiseSuppression: () => void;
  onSetRnnoiseSuppressionLevel: (value: RnnoiseSuppressionLevel) => void;
  onTogglePreRnnEchoCancellation: () => void;
  onTogglePreRnnAutoGainControl: () => void;
  onToggleSelfMonitor: () => void;
  onSetWalkieTalkieEnabled: (value: boolean) => void;
  onSetWalkieTalkieHotkey: (value: string) => void;
  onToggleVoiceSettings: () => void;
  onToggleAudioOutput: () => void;
  onOpenUserSettings: (tab: "profile" | "sound" | "camera") => void;
  onSetVoiceSettingsOpen: (value: boolean) => void;
  onSetAudioOutputMenuOpen: (value: boolean) => void;
  onSetVoiceSettingsPanel: (panel: VoiceSettingsPanel) => void;
  onSetUserSettingsOpen: (value: boolean) => void;
  onSetUserSettingsTab: (value: "profile" | "sound" | "camera" | "server_sounds") => void;
  onSetProfileNameDraft: (value: string) => void;
  onSetSelectedLang: (value: Lang) => void;
  onSetSelectedUiTheme: (value: UiTheme) => void;
  onApplyProfileName: () => Promise<void>;
  onApplyProfileTheme: (value: UiTheme) => Promise<void>;
  onDeleteAccount: () => void;
  onConfirmServerAge: () => void;
  onSetSelectedInputId: (value: string) => void;
  onSetSelectedOutputId: (value: string) => void;
  onSetSelectedVideoInputId: (value: string) => void;
  onSetSelectedInputProfile: (value: InputProfile) => void;
  onRefreshDevices: () => void;
  onRequestMediaAccess: () => void;
  onRequestVideoAccess: () => void;
  onSetMicVolume: (value: number) => void;
  onSetOutputVolume: (value: number) => void;
  onSetServerSoundsMasterVolume: (value: number) => void;
  onSetServerSoundEnabled: (event: ServerSoundEvent, value: boolean) => void;
  onPreviewServerSound: (event: ServerSoundEvent) => void;
  onDisconnectCall: () => void;
  isMobileViewport: boolean;
  inlineSettingsMode?: boolean;
};

export type RoomsPanelProps = {
  t: TranslateFn;
  canCreateRooms: boolean;
  canKickMembers: boolean;
  canManageAudioQuality: boolean;
  roomsTree: RoomsTreeResponse | null;
  roomSlug: string;
  activeChatRoomSlug: string;
  screenShareOwnerByRoomSlug: Record<string, { userId: string | null; userName: string | null }>;
  roomUnreadBySlug: Record<string, number>;
  serverUnreadCount: number;
  currentUserId: string;
  liveRoomMembersBySlug: Record<string, string[]>;
  liveRoomMemberDetailsBySlug: Record<string, PresenceMember[]>;
  memberPreferencesByUserId: Record<string, RoomMemberPreference>;
  voiceMicStateByUserIdInCurrentRoom: Record<string, "muted" | "silent" | "speaking">;
  voiceCameraEnabledByUserIdInCurrentRoom: Record<string, boolean>;
  voiceAudioOutputMutedByUserIdInCurrentRoom: Record<string, boolean>;
  audioMuted: boolean;
  voiceRtcStateByUserIdInCurrentRoom: Record<string, "disconnected" | "connecting" | "connected">;
  voiceMediaStatusSummaryByUserIdInCurrentRoom: Record<string, VoiceMediaStatusSummary>;
  collapsedCategoryIds: string[];
  uncategorizedRooms: Room[];
  archivedRooms: Room[];
  newCategoryTitle: string;
  categoryPopupOpen: boolean;
  newRoomTitle: string;
  newRoomKind: RoomKind;
  newRoomCategoryId: string;
  channelPopupOpen: boolean;
  categorySettingsPopupOpenId: string | null;
  editingCategoryTitle: string;
  channelSettingsPopupOpenId: string | null;
  editingRoomTitle: string;
  editingRoomKind: RoomKind;
  editingRoomCategoryId: string;
  editingRoomNsfw: boolean;
  editingRoomHidden: boolean;
  editingRoomAudioQualitySetting: ChannelAudioQualitySetting;
  categoryPopupRef: RefObject<HTMLDivElement>;
  channelPopupRef: RefObject<HTMLDivElement>;
  onSetCategoryPopupOpen: (value: boolean) => void;
  onSetChannelPopupOpen: (value: boolean) => void;
  onSetNewCategorySlug: (value: string) => void;
  onSetNewCategoryTitle: (value: string) => void;
  onSetNewRoomSlug: (value: string) => void;
  onSetNewRoomTitle: (value: string) => void;
  onSetNewRoomKind: (value: RoomKind) => void;
  onSetNewRoomCategoryId: (value: string) => void;
  onSetEditingCategoryTitle: (value: string) => void;
  onSetEditingRoomTitle: (value: string) => void;
  onSetEditingRoomKind: (value: RoomKind) => void;
  onSetEditingRoomCategoryId: (value: string) => void;
  onSetEditingRoomNsfw: (value: boolean) => void;
  onSetEditingRoomHidden: (value: boolean) => void;
  onSetEditingRoomAudioQualitySetting: (value: ChannelAudioQualitySetting) => void;
  onCreateCategory: (event: FormEvent) => void;
  onCreateRoom: (event: FormEvent) => void;
  onOpenCreateChannelPopup: (categoryId?: string | null) => void;
  onOpenCategorySettingsPopup: (categoryId: string, categoryTitle: string) => void;
  onOpenChannelSettingsPopup: (room: Room) => void;
  onSaveCategorySettings: (event: FormEvent) => void;
  onMoveCategory: (direction: "up" | "down") => void;
  onDeleteCategory: () => void;
  onSaveChannelSettings: (event: FormEvent) => void;
  onMoveChannel: (direction: "up" | "down") => void;
  onClearChannelMessages: (room: Room) => void;
  onDeleteChannel: (room: Room) => void;
  onRestoreChannel: (room: Room) => void;
  onDeleteChannelPermanent: (room: Room) => void;
  onToggleCategoryCollapsed: (categoryId: string) => void;
  onJoinRoom: (slug: string) => void;
  onOpenRoomChat: (slug: string) => void;
  onKickRoomMember: (roomSlug: string, userId: string, userName: string) => void;
  onMoveRoomMember: (fromRoomSlug: string, toRoomSlug: string, userId: string, userName: string) => void;
  onSaveMemberPreference: (targetUserId: string, input: { volume: number; note: string }) => Promise<void>;
  onLoadServerMemberProfile: (userId: string) => Promise<{
    userId: string;
    name: string;
    email: string;
    joinedAt: string;
    role: "owner" | "admin" | "member";
    customRoles: Array<{ id: string; name: string }>;
    hiddenRoomAccess: Array<{ roomId: string; roomSlug: string; roomTitle: string }>;
    hiddenRoomsAvailable: Array<{ roomId: string; roomSlug: string; roomTitle: string; hasAccess: boolean }>;
  } | null>;
  onLoadServerRoles: () => Promise<Array<{ id: string; name: string; isBase: boolean }>>;
  onSetServerMemberCustomRoles: (userId: string, roleIds: string[]) => Promise<boolean>;
  onSetServerMemberHiddenRoomAccess: (userId: string, roomIds: string[]) => Promise<boolean>;
  onSetRoomNotificationMutePreset: (roomId: string, preset: "1h" | "8h" | "24h" | "forever" | "off") => Promise<void>;
};
