import type { UserDockProps } from "./types";
import { UserDockControls } from "./userDock/UserDockControls";
import { UserDockSettingsOverlay } from "./userDock/UserDockSettingsOverlay";

export function UserDock({
  t,
  user,
  currentRoomSupportsRtc,
  currentRoomSupportsVideo,
  currentRoomTitle,
  callStatus,
  localVoiceMediaStatusSummary,
  lastCallPeer,
  remoteAudioAutoplayBlocked,
  screenShareActive,
  screenShareOwnedByCurrentUser,
  canStartScreenShare,
  noiseSuppressionEnabled,
  rnnoiseSuppressionLevel,
  rnnoiseRuntimeStatus,
  preRnnEchoCancellationEnabled,
  preRnnAutoGainControlEnabled,
  selfMonitorEnabled,
  walkieTalkieEnabled,
  walkieTalkieHotkey,
  cameraEnabled,
  micMuted,
  audioMuted,
  audioOutputMenuOpen,
  voiceSettingsOpen,
  userSettingsOpen,
  userSettingsTab,
  voiceSettingsPanel,
  profileUsername,
  profileNameDraft,
  profileEmail,
  profileSaving,
  profileStatusText,
  deleteAccountPending,
  deleteAccountStatusText,
  serverAgeLoading,
  serverAgeConfirmedAt,
  serverAgeConfirming,
  selectedLang,
  selectedUiTheme,
  languageOptions,
  inputOptions,
  outputOptions,
  videoInputOptions,
  selectedInputId,
  selectedOutputId,
  selectedVideoInputId,
  selectedInputProfile,
  inputProfileLabel,
  currentInputLabel,
  micVolume,
  outputVolume,
  serverSoundsMasterVolume,
  serverSoundsEnabled,
  micTestLevel,
  mediaDevicesState,
  mediaDevicesHint,
  audioOutputAnchorRef,
  voiceSettingsAnchorRef,
  userSettingsRef,
  onToggleMic,
  onToggleAudio,
  onToggleCamera,
  onToggleScreenShare,
  onToggleNoiseSuppression,
  onSetRnnoiseSuppressionLevel,
  onTogglePreRnnEchoCancellation,
  onTogglePreRnnAutoGainControl,
  onToggleSelfMonitor,
  onSetWalkieTalkieEnabled,
  onSetWalkieTalkieHotkey,
  onToggleVoiceSettings,
  onToggleAudioOutput,
  onOpenUserSettings,
  onSetVoiceSettingsOpen,
  onSetAudioOutputMenuOpen,
  onSetVoiceSettingsPanel,
  onSetUserSettingsOpen,
  onSetUserSettingsTab,
  onSetProfileNameDraft,
  onSetSelectedLang,
  onSetSelectedUiTheme,
  onApplyProfileName,
  onApplyProfileTheme,
  onDeleteAccount,
  onConfirmServerAge,
  onSetSelectedInputId,
  onSetSelectedOutputId,
  onSetSelectedVideoInputId,
  onSetSelectedInputProfile,
  onRefreshDevices,
  onRequestMediaAccess,
  onRequestVideoAccess,
  onSetMicVolume,
  onSetOutputVolume,
  onSetServerSoundsMasterVolume,
  onSetServerSoundEnabled,
  onPreviewServerSound,
  onDisconnectCall,
  isMobileViewport,
  inlineSettingsMode = false
}: UserDockProps) {
  const mediaDevicesUnavailable = mediaDevicesState !== "ready";
  const mediaControlsLocked = mediaDevicesState === "denied";
  const mediaDevicesWarningText = mediaDevicesHint || t("settings.mediaUnavailable");
  const modalBarCount = 42;
  const modalActiveBars = Math.min(modalBarCount, Math.round(micTestLevel * modalBarCount));
  void localVoiceMediaStatusSummary;
  void callStatus;
  void lastCallPeer;
  void screenShareOwnedByCurrentUser;
  void currentRoomTitle;
  return (
    <>
      <div className={`user-dock relative z-20 mt-auto flex min-h-0 flex-col gap-4 ${inlineSettingsMode ? "hidden" : ""}`}>
        <UserDockControls
          t={t}
          currentRoomSupportsRtc={currentRoomSupportsRtc}
          currentRoomSupportsVideo={currentRoomSupportsVideo}
          screenShareActive={screenShareActive}
          screenShareOwnedByCurrentUser={screenShareOwnedByCurrentUser}
          canStartScreenShare={canStartScreenShare}
          noiseSuppressionEnabled={noiseSuppressionEnabled}
          cameraEnabled={cameraEnabled}
          micMuted={micMuted}
          audioMuted={audioMuted}
          audioOutputMenuOpen={audioOutputMenuOpen}
          voiceSettingsOpen={voiceSettingsOpen}
          voiceSettingsPanel={voiceSettingsPanel}
          inputOptions={inputOptions}
          outputOptions={outputOptions}
          videoInputOptions={videoInputOptions}
          selectedInputId={selectedInputId}
          selectedOutputId={selectedOutputId}
          selectedVideoInputId={selectedVideoInputId}
          currentInputLabel={currentInputLabel}
          micVolume={micVolume}
          walkieTalkieEnabled={walkieTalkieEnabled}
          walkieTalkieHotkey={walkieTalkieHotkey}
          outputVolume={outputVolume}
          micTestLevel={micTestLevel}
          mediaDevicesState={mediaDevicesState}
          audioOutputAnchorRef={audioOutputAnchorRef}
          voiceSettingsAnchorRef={voiceSettingsAnchorRef}
          onToggleMic={onToggleMic}
          onToggleAudio={onToggleAudio}
          onToggleCamera={onToggleCamera}
          onToggleScreenShare={onToggleScreenShare}
          onToggleNoiseSuppression={onToggleNoiseSuppression}
          onToggleVoiceSettings={onToggleVoiceSettings}
          onToggleAudioOutput={onToggleAudioOutput}
          onOpenUserSettings={onOpenUserSettings}
          onSetVoiceSettingsOpen={onSetVoiceSettingsOpen}
          onSetAudioOutputMenuOpen={onSetAudioOutputMenuOpen}
          onSetVoiceSettingsPanel={onSetVoiceSettingsPanel}
          onSetSelectedInputId={onSetSelectedInputId}
          onSetSelectedOutputId={onSetSelectedOutputId}
          onSetSelectedVideoInputId={onSetSelectedVideoInputId}
          onRequestVideoAccess={onRequestVideoAccess}
          onSetMicVolume={onSetMicVolume}
          onSetWalkieTalkieEnabled={onSetWalkieTalkieEnabled}
          onSetWalkieTalkieHotkey={onSetWalkieTalkieHotkey}
          onSetOutputVolume={onSetOutputVolume}
          onDisconnectCall={onDisconnectCall}
          isMobileViewport={isMobileViewport}
          mediaDevicesUnavailable={mediaDevicesUnavailable}
          mediaControlsLocked={mediaControlsLocked}
          mediaDevicesWarningText={mediaDevicesWarningText}
        />
      </div>

      <UserDockSettingsOverlay
        t={t}
        user={user}
        userSettingsOpen={userSettingsOpen}
        inlineSettingsMode={inlineSettingsMode}
        userSettingsRef={userSettingsRef}
        userSettingsTab={userSettingsTab}
        onSetUserSettingsOpen={onSetUserSettingsOpen}
        onSetUserSettingsTab={onSetUserSettingsTab}
        profileUsername={profileUsername}
        profileNameDraft={profileNameDraft}
        profileEmail={profileEmail}
        profileSaving={profileSaving}
        profileStatusText={profileStatusText}
        deleteAccountPending={deleteAccountPending}
        deleteAccountStatusText={deleteAccountStatusText}
        serverAgeLoading={serverAgeLoading}
        serverAgeConfirmedAt={serverAgeConfirmedAt}
        serverAgeConfirming={serverAgeConfirming}
        onApplyProfileName={onApplyProfileName}
        onApplyProfileTheme={onApplyProfileTheme}
        onDeleteAccount={onDeleteAccount}
        onConfirmServerAge={onConfirmServerAge}
        onSetProfileNameDraft={onSetProfileNameDraft}
        selectedLang={selectedLang}
        selectedUiTheme={selectedUiTheme}
        languageOptions={languageOptions}
        onSetSelectedLang={onSetSelectedLang}
        onSetSelectedUiTheme={onSetSelectedUiTheme}
        inputOptions={inputOptions}
        outputOptions={outputOptions}
        selectedInputId={selectedInputId}
        selectedOutputId={selectedOutputId}
        onSetSelectedInputId={onSetSelectedInputId}
        onSetSelectedOutputId={onSetSelectedOutputId}
        onRequestMediaAccess={onRequestMediaAccess}
        onRefreshDevices={onRefreshDevices}
        micVolume={micVolume}
        outputVolume={outputVolume}
        onSetMicVolume={onSetMicVolume}
        onSetOutputVolume={onSetOutputVolume}
        selectedVideoInputId={selectedVideoInputId}
        videoInputOptions={videoInputOptions}
        onSetSelectedVideoInputId={onSetSelectedVideoInputId}
        onRequestVideoAccess={onRequestVideoAccess}
        serverSoundsMasterVolume={serverSoundsMasterVolume}
        onSetServerSoundsMasterVolume={onSetServerSoundsMasterVolume}
        serverSoundsEnabled={serverSoundsEnabled}
        onSetServerSoundEnabled={onSetServerSoundEnabled}
        onPreviewServerSound={onPreviewServerSound}
        mediaDevicesUnavailable={mediaDevicesUnavailable}
        mediaControlsLocked={mediaControlsLocked}
        mediaDevicesWarningText={mediaDevicesWarningText}
        noiseSuppressionEnabled={noiseSuppressionEnabled}
        rnnoiseSuppressionLevel={rnnoiseSuppressionLevel}
        rnnoiseRuntimeStatus={rnnoiseRuntimeStatus}
        preRnnEchoCancellationEnabled={preRnnEchoCancellationEnabled}
        preRnnAutoGainControlEnabled={preRnnAutoGainControlEnabled}
        selfMonitorEnabled={selfMonitorEnabled}
        walkieTalkieEnabled={walkieTalkieEnabled}
        walkieTalkieHotkey={walkieTalkieHotkey}
        onSetWalkieTalkieEnabled={onSetWalkieTalkieEnabled}
        onSetWalkieTalkieHotkey={onSetWalkieTalkieHotkey}
        onToggleSelfMonitor={onToggleSelfMonitor}
        onToggleNoiseSuppression={onToggleNoiseSuppression}
        onSetRnnoiseSuppressionLevel={onSetRnnoiseSuppressionLevel}
        onTogglePreRnnEchoCancellation={onTogglePreRnnEchoCancellation}
        onTogglePreRnnAutoGainControl={onTogglePreRnnAutoGainControl}
        modalBarCount={modalBarCount}
        modalActiveBars={modalActiveBars}
      />
    </>
  );
}
