export type AuthMode = "sso" | "local";

export type AppConfig = {
  port: number;
  databaseUrl: string;
  redisUrl: string;
  jwtSecret: string;
  jwtExpiresIn: string;
  corsOrigin: string;
  authMode: AuthMode;
  authSsoBaseUrl: string;
  authSsoRequestTimeoutMs: number;
  authCookieMode: boolean;
  authSessionCookieName: string;
  authSessionCookieSecure: boolean;
  authSessionCookieSameSite: "Lax" | "Strict" | "None";
  authSessionCookieDomain: string;
  authSessionCookiePath: string;
  authSessionCookieMaxAgeSec: number;
  smokeAuthBootstrapEnabled: boolean;
  allowedReturnHosts: string[];
  superAdminEmail: string;
  appVersion: string;
  appBuildSha: string;
  apiServeStatic: boolean;
  rtcFeatureInitialStateReplay: boolean;
  rtcMediaTopologyDefault: "livekit";
  livekitEnabled: boolean;
  livekitUrl: string;
  livekitApiKey: string;
  livekitApiSecret: string;
  livekitTokenTtlSec: number;
  chatImageMaxDataUrlLength: number;
  chatImageMaxSide: number;
  chatImageJpegQuality: number;
  chatUploadMaxSizeBytes: number;
  chatLargeFileThresholdBytes: number;
  chatLargeFileRetentionDays: number;
  chatBackupMaxFileSizeBytes: number;
  chatUploadAllowedMimeTypes: string[];
  chatUploadInitTtlSec: number;
  chatStorageProvider: "localfs" | "minio";
  chatMinioEndpoint: string;
  chatMinioRegion: string;
  chatMinioAccessKey: string;
  chatMinioSecretKey: string;
  chatMinioBucket: string;
  chatMinioForcePathStyle: boolean;
  chatObjectStoragePublicBaseUrl: string;
  webPushEnabled: boolean;
  webPushSubject: string;
  webPushPublicKey: string;
  webPushPrivateKey: string;
};
