export type AuthMode = "sso" | "local";

export type AppConfig = {
  port: number;
  databaseUrl: string;
  redisUrl: string;
  jwtSecret: string;
  jwtExpiresIn: string;
  corsOrigin: string;
  authMode: AuthMode;
  authSsoBaseUrl: string;
  authCookieMode: boolean;
  authSessionCookieName: string;
  authSessionCookieSecure: boolean;
  authSessionCookieSameSite: "Lax" | "Strict" | "None";
  authSessionCookieDomain: string;
  authSessionCookiePath: string;
  authSessionCookieMaxAgeSec: number;
  allowedReturnHosts: string[];
  superAdminEmail: string;
  appVersion: string;
  appBuildSha: string;
  apiServeStatic: boolean;
  rtcFeatureInitialStateReplay: boolean;
  rtcMediaTopologyDefault: "livekit";
  livekitEnabled: boolean;
  livekitUrl: string;
  livekitApiKey: string;
  livekitApiSecret: string;
  livekitTokenTtlSec: number;
};
